### ISSUE TITLE
Community calls?

### ISSUE THREAD

**Issue by vmx** [ipld/libipld#10]
There is increasing interest in having a proper Rust IPLD implementation from different people/parties. Would there be interest in doing video calls from time to time (e.g. every two weeks) where everyone can join, to coordinate things, which is sometimes easier doing sync? And of course also if you have questions, want to help or just want to know what others have to say.

If there's interest I can set something up and try to find a spot that works across timezones.

Though I want to make clear that discussions and decisions should happen async on this repository, this would just be some additional way of engaging with the community.

**Comment by Gozala** [comment]
I don't mind having those, however I'm not sure I'd be able to dial in every time. I do however would love nearly real-time communication channel to discuss things when necessary.

**Comment by dvc94ch** [comment]
I prefer asynchronous communication. How about using the rust-ipfs riot channel for rust-ipld discussions too?

**Comment by dvc94ch** [comment]
As @vmx has joined riot, I think this can be closed for now
