### ISSUE TITLE
looking for new co-maintainers

### ISSUE THREAD

**Issue by dvc94ch** [ipld/libipld#112]
actyx is using it in production and I will continue to maintain it for as long as actyx uses it. personally however I've moved on to other projects.

**Comment by molekilla** [comment]
we are using it, https://github.com/Electronic-Signatures-Industries/rust-xdv-protocol

@block-mon @lkrayola 


we would like to contribute, lmk

**Comment by dvc94ch** [comment]
Hi @molekilla 

I added you as an external contributor to this repo, I guess that's sufficient to get you started. There is some low hanging fruit in #110 and #111

Cheers

**Comment by molekilla** [comment]
can you also add @lkrayola, thanks

**Comment by dvc94ch** [comment]
done
