### ISSUE TITLE
Test codecs against IPLD test fixtures

### ISSUE THREAD

**Issue by vmx** [ipld/libipld#113]
Finally there are some test fixtures for DAG-CBOR, DAG-JSON and DAG-PB at https://github.com/ipld/codec-fixtures. It would be great to test against those, to make sure things are compatible to other IPLD implementations. The code running those would probably live at that repo.

**Comment by molekilla** [comment]
@vmx `rust` folder then will be in https://github.com/ipld/codec-fixtures ? will need access too. thanks

**Comment by vmx** [comment]
Yes, it will be a `rust` folder over there. A pull request would be great :)

**Comment by vmx** [comment]
To prevent double efforts: I'll be working on this now.

**Comment by vmx** [comment]
This is done now! What DAG-CBOR and DAG-JSON all pass, hardly any from DAG-PB does, there is a separate issue open for that: https://github.com/ipld/libipld/issues/139.
