### ISSUE TITLE
Implement strict DagCbor spec

### ISSUE THREAD

**Issue by Stebalien** [ipld/libipld#119]
See: https://github.com/ipld/ipld/blob/master/specs/codecs/dag-cbor/spec.md#strictness

- no undefined major type.
- no Indefinite length arrays, etc.
- minimal integer encoding.
- f64 only.
- no nan, infinity, etc.

**Comment by vmx** [comment]
I think that issue can be closed, given that the most recent version passed the [IPLD codec fixtures](https://bugzilla.mozilla.org/show_bug.cgi?id=1792370).
