### ISSUE TITLE
Switching from failure to thiserror?

### ISSUE THREAD

**Issue by vmx** [ipld/libipld#12]
Currently `failure` is used. Though as Rust's errors improved there are new crates out there. I suggest to switch to [thiserror](https://github.com/dtolnay/thiserror). I really mean thiserror and not [Anyhow](https://github.com/dtolnay/anyhow) I think we should have fine-grained error handling and not a catch-all approach.

In case people agree, this would be a good issue for someone who wants to start contributing.

**Comment by dvc94ch** [comment]
Why don't we just impl Debug, Display, Error and From manually? I'm kind of fed up with the error crate of the week approach.

**Comment by vmx** [comment]
That works as well. Though this is what "thiserror" is doing with less boilerplate. So one approach (if someone wants to tackle it) could also be using "thiserror", running `cargo expand` and just use that output. I'd personally would use "thiserror" for simplicity, but a manual implementation is also fine.

**Comment by vmx** [comment]
Here's an example of switching from manual error message to `thiserror`: https://github.com/filecoin-project/bellman/pull/64/files. I quite like that.

**Comment by dvc94ch** [comment]
thiserror is ok with me, as unlike failure it generates what one would write manually, so there should be no compatibility issues.
