### ISSUE TITLE
dag-cbor-derive fails to understand package rename

### ISSUE THREAD

**Issue by dignifiedquire** [ipld/libipld#131]
I am using an alias of `ipld = {package = "libipld"}` to import, but getting the error message of

```
error[E0433]: failed to resolve: use of undeclared crate or module `libipld`
  --> car/src/lib.rs:14:26
   |
14 | #[derive(Debug, Default, DagCbor, PartialEq)]
   |                          ^^^^^^^ use of undeclared crate or module `libipld`
```

**Comment by vmx** [comment]
In case you are blocked by this, see https://github.com/ipld/libipld/compare/wip-fix-derive-rename. I'd like to get #129 merged before I PR this one properly.
