### ISSUE TITLE
Make DAG-PB spec compliant

### ISSUE THREAD

**Issue by vmx** [ipld/libipld#139]
The DAG-PB codec isn't spec compliant yet. We have test fixtures at https://github.com/ipld/codec-fixtures which can be used to get there ~(a Rust runner is in the works at https://github.com/ipld/codec-fixtures/pull/25)~ (there is already a Rust test runner there that skips the DAG-PB tests at the moment).

**Comment by vmx** [comment]
There is a [JS implementation](https://github.com/ipld/js-dag-pb) and a [Go implementation](https://github.com/ipld/go-codec-dagpb) that are both spec compliant which encode and decode the the Protocol Buffers manually. This would be the preferred way to fix this issue. Both can serve as a template for anyone wanting to tackle this issue.

**Comment by dignifiedquire** [comment]
What's the actual failure? I suspect that protobuf field ordering is the problem, which is just bad design in the original spec and on the decoding side it shouldn't matter, and on encoding it only matters if you need exact hash matching

**Comment by vmx** [comment]
> on encoding it only matters if you need exact hash matching

This is what a spec compliant codec should support. I haven't looked into the details, I only know that the test fixtures don't pass.

**Comment by dignifiedquire** [comment]
> This is what a spec compliant codec should support.

Then heads up, iroh will not be spec compliant. For the reason above about the spec wanting non standard protobuf encoding.

**Comment by vmx** [comment]
> For the reason above about the spec wanting non standard protobuf encoding.

No. The spec is just describing what the original Go implementation for DAG-PB was doing. It was using the usual Protocol Buffers implementation, so I'd call it standard protobuf encoding.

**Comment by vmx** [comment]
This has long been resolved by https://github.com/ipld/libipld/pull/170!
