### ISSUE TITLE
Block API

### ISSUE THREAD

**Issue by vmx** [ipld/libipld#14]
There is a new [Block API in the JavaScript IPLD](https://github.com/ipld/js-block#block-api) implementation, which I find quite nice.

I was thinking about using a similar one for Rust IPLD. I'm still implementing/playing around with the idea, but I thought I publish a draft early on:

Block
------

A `Block` is an IPLD object together with a CID. The data can be encoded
and decoded.

All operations are cached. This means that encoding, decoding and CID
calculation happens at most once. All subsequent calls will use a cached
version.

Methods
-------

#### `pub fn new<R>(cid: Cid, raw: Vec<u8>) -> Self where R: Registry`

Create a new `Block` from the given CID and raw binary data.

It needs a registry that contains codec and hash algorithms
implementations in order to be able to decode the data into IPLD.

#### `pub fn encoder(node: Ipld, codec: &'a dyn Codec<Error = Error>, hash_alg: &'a dyn Hash) -> Self`

Create a new `Block` from the given IPLD object, codec and hash
algorithm.

No computation is done, the CID creation and the encoding will only be
performed when the corresponding methods are called.

#### `pub fn decoder(aw: Vec<u8>, codec: &'a dyn Codec<Error = Error>, hash_alg: &'a dyn Hash) -> Self`

Create a new `Block` from encoded data, codec and hash algorithm.

No computation is done, the CID creation and the decoding will only be
performed when the corresponding methods are called.

#### `pub fn decode(&mut self) -> Ipld`

Decode the `Block` into an IPLD object.

The actual decoding is only performed if the object doesn't have a copy
of the IPLD object yet. If that method was called before, it returns the
cached result.

#### `pub fn encode(&mut self) -> Vec<u8>`

Encode the `Block` into raw binary data.

The actual encoding is only performed if the object doesn't have a copy
of the encoded raw binary data yet. If that method was called before, it
returns the cached result.

#### `pub fn cid(&mut self) -> Cid`

Calculate the CID of the `Block`.

The CID is calculated from the encoded data. If it wasn't encoded
before, that operation will be performed. If the encoded data is already
available, from a previous call of `encode()` or because the `Block` was
instantiated via `encoder()`, then it isn't re-encoded.

**Comment by dvc94ch** [comment]
it seems like you want to have a struct like this:
```rust
struct Block {
    cid: Cid,
    raw: Vec<u8>,
    ipld: Option<Ipld>,
}
```
in this case why does `cid(&mut self)` need to be mut? we should handle multithreading transparently, so to avoid having the user wrap a block in an Arc<Mutex>> we need to make sure that the Block impl Clone + Send + Sync and doesn't use &mut self.

There should also be a way to encode/decode straight to a struct without having ipld as an intermediate representation.

I'm also not really sure that a block as a (cid, bytes) tuple provides a meaningful abstraction, as I tried various `Block` structs and then decided that having a store trait was the more sensible approach. The `Block` struct was only getting in the way and not really adding anything.

**Comment by vmx** [comment]
The `Block` I currently have looks like that:

```rust
pub struct Block<'a> {
    cid: Option<Cid>,
    raw: Option<Vec<u8>>,
    node: Option<Ipld>,
    codec: &'a dyn Codec<…>,
    hash_alg: &'a dyn Hash,
}
```

The reasons for the `mut` in my current code is that if you call `cid()` and so far you only have seen the decoded version, you need to encode it first in order to get the CID. The encoded bytes are then stored in `raw`, hence the `mut`.

**Comment by koivunej** [comment]
Looking at the proposed structs I feel like I not able to see the usecase for keeping all of these components together in a single struct? I can currently come up with two-ish usecases for blocks in general:

 * encoding from some other representation to bytes
 * (generating in some $app_specific_manner)
 * decoding from bytes to some other representation
 * (consuming in some $app_specific_manner)

As in, the `(codec, hash_alg)` is only needed to generate a `(cid, encoded_bytes)` from an AST/DOM/struct representation of an "ipld" [document]. The other direction(s) from `(cid, encoded_bytes)` to AST/DOM or struct representation would need looking up the codec from cid and letting it turn the bytes into the $representation. The app specific use cases are pretty much `Vec<u8>` and optional precalculated CID (for example: calculated while serializing).

Why/when it would be useful to keep all of these together in a single type?

I am using AST/DOM to mean the recursive `enum Ipld { ... }`.

**Comment by vmx** [comment]
@koivunej The idea is that for the API it doesn't matter it which form you have the current data. Whether it's AST/DOM or encoded bytes. You can always get the other form out of it. Sometimes it needs some processing, something it just returns the existing values. When using the API you don't have to care about that.

**Comment by mikeal** [comment]
> Looking at the proposed structs I feel like I not able to see the usecase for keeping all of these components together in a single struct?

I can speak pretty well to how this ends up being used in JavaScript.

Once you start layering different interfaces you end up with a lot of actors doing encoding, decoding, and/or hashing. Combining these into a single interface means that you can provide a common API to pass around that normalizes and caches all of this.

This also means that you can pass a single interface to any actor, regardless of whether or not they want the encoded state, the decoded state, or the content address for linking. All of these states can be generated just-in-time and then cached for future consumers of the block.

**Comment by dvc94ch** [comment]
I still think that from a user perspective adding `#[derive(DagCbor)]` to a `struct` or `enum` is the most useful abstraction, but there's no reason that they can't both be supported. The macro would create a `Block` with `new` when encoding and read the bytes directly when decoding.

In the current ipld api we have the following:
```rust
fn read(&self, &Cid) -> Result<Box<[u8]>>;
fn read_ipld(&self, &Cid) -> Result<Ipld>;
fn read_cbor<T: ReadCbor>(&self, &Cid) -> Result<T>;

fn write(&self, &Cid, &[u8]) -> Result<()>;
fn write_cbor<H: Hash, T: WriteCbor>(&self, t: T) -> Result<Cid>;
```

So that would change to something like this:
```rust
fn read(&self, &Cid) -> Result<Block>;
fn read_cbor<T: ReadCbor>(&self, &Cid) -> Result<T>;

fn write(&self, &Block) -> Result<()>;
fn write_cbor<H: Hash, T: WriteCbor>(&self, t: T) -> Result<Cid>;
```

In general I don't see applications really mixing binary/ipld/rust representations, as most will use a native rust representation and a few will use the binary or ipld representation, for example for creating an archive or a generic block viewer.

**Comment by vmx** [comment]
> I still think that from a user perspective adding `#[derive(DagCbor)]` to a `struct` or `enum` is the most useful abstraction

I agree. Those derives will then have annotations on how to encode the Rust data structures into the IPLD Data Model.

> In general I don't see applications really mixing binary/ipld/rust representations

When you want to add data to some DAG, you would have your current data as Rust/IPLD and while you are traversing to the right location, you would encounter binary blocks.

**Comment by koivunej** [comment]
Thanks @mikeal for joining in!

> Once you start layering different interfaces you end up with a lot of actors doing encoding, decoding, and/or hashing. Combining these into a single interface means that you can provide a common API to pass around that normalizes and caches all of this.

While it is difficult to discuss this level of API design as I haven't yet reached the same point in the implementation at all as you three, my initial reaction to this was "could the stronger type system guide us to another design", as in, if some component needs a raw version of a block, then it expects bytes in some form, if a cid, then it expects a cid, and so on.

While writing the above, @vmx replied:

> > In general I don't see applications really mixing binary/ipld/rust representations
>
> [...] while you are traversing to the right location, you would encounter binary blocks.

An alternative to binary blocks would be to open the link as the `T` in Davids suggested `store.read_cbor<T>(&cid)` where `T` is the expected type for the block contents deriving `DagCbor`. This way the underlying bytes would not need to be exposed. For example: 

```
let next = store.read_cbor<UserType>(&cid).await?;
```

**Comment by vmx** [comment]
> let next = store.read_cbor<UserType>(&cid).await?;

I was wondering what `store` is about and then found it in an [older comment from @dvc94ch](https://github.com/ipfs-rust/rust-ipld/issues/14#issuecomment-595283220) I missed to reply to.

> I'm also not really sure that a block as a (cid, bytes) tuple provides a meaningful abstraction, as I tried various `Block` structs and then decided that having a store trait was the more sensible approach. The `Block` struct was only getting in the way and not really adding anything.

The current direction of IPLD implementations is to move away from having block storage as a central piece. The data should be able to come from anywhere, memory, network or disk. Hence the idea of the Block API came up. You get the block from "somewhere" and then work with it.

**Comment by mikeal** [comment]
One thing that might be lost in translation between different languages and abstractions here is that a `Block` instance is, and I’m using the term loosely, immutable once instantiated. By “immutable” i mean that the value returned by any method is static after instantiation. For instance, you can’t ask a `dag-cbor` block for the `dag-json` encode. This is important because you can’t safely link to a block that might mutate in any way.

> In general I don't see applications really mixing binary/ipld/rust representations, as most will use a native rust representation and a few will use the binary or ipld representation, for example for creating an archive or a generic block viewer.

My experience is quite the opposite. You end up creating all kinds of pipelines for reading and writing data, many of which need to link to different parts of the data, store the data, or just read the data. All of these require a mix of the CID, encoded and decoded representations.

> The current direction of IPLD implementations is to move away from having block storage as a central piece. The data should be able to come from anywhere, memory, network or disk. Hence the idea of the Block API came up. You get the block from "somewhere" and then work with it.

I can speak a little more to this.

In the latest revisions of the IPLD libraries one thing we wanted to do was move away from requiring a storage interface for the low level interfaces. There’s a lot you do with data that doesn’t require storage. Most libraries produce data and/or read data. Few of them need an entire read/write interface and passing in the entire abstraction changes how flexible these can be.

For instance, the new JS IPLD libraries that produce data return async generators that yield block instances. This allows the user to do whatever they want with them, and often what they want is not necessarily to store them (they may want to write them to the network or even throw them out in certain testing and validation use cases).

For the APIs that need to read blocks from *somewhere* (storage, network, etc) we pass in a simple `get(cid)` method than returns a block instance. This is a simple abstraction anyone can write inline and it has turned out quite nice in practice.

**Comment by mikeal** [comment]
One last and rather important point I somehow forgot. Part of the value of IPLD is to be codec agnostic. That flexibility is lost if you build on codec specific interfaces and a lot of thought went into how the `Block` API could maintain that flexibility throughout the stack. It’s probably worth pulling in @Gozala since he provided a lot of the insight here when we were designing the new JS Block interface.

**Comment by dvc94ch** [comment]
> pass in a simple get(cid)

more methods are required no? For the multiblock ipld vec, it gets loaded from an ipns entry. Then it's modified requiring putting/pinning the new blocks and unpinning the old ones and finally the ipns entry needs to be updated. And ideally all this should be done in an atomic way so that the store state is consistent even when gc is running in the background.

**Comment by koivunej** [comment]
Thanks for you both for added context, this definelty clarifies the ambitions here. I might need to take a closer look at the `js-ipld` repo next, I've mostly looked at `go-ipld-prime` thinking it was the latest developments.

**Comment by warpfork** [comment]
> In general I don't see applications really mixing binary/ipld/rust representations, as most will use a native rust representation and a few will use the binary or ipld representation, for example for creating an archive or a generic block viewer.

So the hope I hold for this stuff is: those two kinds of usage should be easy to intermingle, and it should be possible to write fairly generic code that targets the "data model", and it should work over _whatever_ the implementation is, whether it be rust native structs, some general ipld library data holder type, or whatever.

It's true that many applications will pick _either_ rust native structs with annotations/derives as the in-memory format of note, _or_ they'll pick some ipld library data holder if they don't know what their data is in advance.  But we shouldn't discount applications that might do both (say, use native structs for one part of the application core, but use freeform data in another part that has more complicated user-provided data); and even if one application doesn't do both, it would certainly be nice to be able to write libraries work when handling data with either category of in-memory layout (Selectors come to mind!).

So for this reason I don't know if something like `#[derive(DagCbor)]` is going to be either necessary nor sufficient.  It might turn out that we need a set of derives that make a standard Node interface (so libraries like Selectors can be built)... and then from there, codecs can work over that interface... and so we then quietly lose the need to attach codec-specific derives to anything.  Maybe.  Speculating.  Dunno for sure.

I'm not going to claim to know for sure how to best structure this stuff in rust.  Just some "2 cents" considerations.

**Comment by aphelionz** [comment]
Not an expert but some high level thoughts: it seems like by implementing a set of independent traits one can "eat your cake and have it too" while both keeping the code idiomatic to Rust and also achieving the API signature that you want / are used to.

I think some careful thought about how to design the individual traits and as much helpful context we can get us gonna be the trick here. This also might be something one might be able to reason about and experiment with either in the tests or in the examples folder, since it's hard to design all this abstractly without building toward a use case or two, no matter how contrived and simple.

**Comment by dvc94ch** [comment]
I'm warming up to the block api, but so that the ipld-collections remain independent of the store, I think a store api is also needed as mentioned in my previous comment.

**Comment by vmx** [comment]
> I think a store api is also needed as mentioned in my previous comment.

I agree that some store API is needed, it just shouldn't be tightly coupled (as explained in many comments above).

**Comment by vmx** [comment]
> I might need to take a closer look at the `js-ipld` repo next, I've mostly looked at `go-ipld-prime` thinking it was the latest developments.

`go-ipld-prime` are the latest developments. On the JS side the latest developments are *not* in `js-ipld` but split across repos. Most notable here are:

 - https://github.com/ipld/js-block
 - https://github.com/ipld/js-codec-interface
 - https://github.com/ipld/js-get-codec

**Comment by dvc94ch** [comment]
What do you mean by thightly coupled? Tightly coupled to what?

**Comment by vmx** [comment]
> What do you mean by thightly coupled? Tightly coupled to what?

Tightly coupled to traversal and data generation, hence the Block API.

**Comment by dvc94ch** [comment]
Would #27 be complementary to a block api, or an alternative?

**Comment by dvc94ch** [comment]
Also reading the proposal again, the concept of a registry is weird in a compiled language. What's wrong with something like this:
```rust
match codec {
    #[cfg(feature = "cbor")]
    cbor => cbor.encode()
}
```

**Comment by vmx** [comment]
> Would #27 be complementary to a block api, or an alternative?

Could be both, I need to take a closer look. I'm close (as in this week) to having something working which illustrates the idea behind the block API. It would be great if we could wait a bit before digging into #27.

**Comment by vmx** [comment]
> Also reading the proposal again, the concept of a registry is weird in a compiled language. What's wrong with something like this:

The concept of the registry is something I thought we would need, but that's not the case anymore since the refactoring of Multhash (https://github.com/multiformats/rust-multihash/pull/60) and Cid (https://github.com/multiformats/rust-cid/pull/50) using generics. Expect an update to this proposal, this week.

**Comment by vmx** [comment]
> Expect an update to this proposal, this week.

Next week :-/

**Comment by vmx** [comment]
I took the time to actually implement it within a small demo application. The Block API can be found here: https://github.com/vmx/rust-dagbuilder/blob/f7f0c00b96074f6aa6a5aeef0b327b35d73dea72/src/block.rs.

Usage of that API happens in the `create_block()` function: https://github.com/vmx/rust-dagbuilder/blob/f7f0c00b96074f6aa6a5aeef0b327b35d73dea72/src/main.rs#L80-L119

The interesting thing is that `create_block()` returns a new `Block`, but in one case it's created from an IPLD object (https://github.com/vmx/rust-dagbuilder/blob/f7f0c00b96074f6aa6a5aeef0b327b35d73dea72/src/main.rs#L99) and the other time from a still encoded data blob (https://github.com/vmx/rust-dagbuilder/blob/f7f0c00b96074f6aa6a5aeef0b327b35d73dea72/src/main.rs#L103). Though using the `Block` afterwards is the same API, the conversion to bytes or an Ipld object will happen internally when needed. Calling `cid()` (https://github.com/vmx/rust-dagbuilder/blob/f7f0c00b96074f6aa6a5aeef0b327b35d73dea72/src/main.rs#L111) would be an example.

**Comment by dvc94ch** [comment]
@vmx, should we leave this for an external crate? If so we could close this issue

**Comment by vmx** [comment]
I want this eventually be part of IPLD, but for now I think it's OK to have it as an external crate. I'd keep the issue open, but if you like to close it, I can also re-open once it's there.

**Comment by dvc94ch** [comment]
I think the ipld-block-builder is what you'd want if you are using native types, so I'd prefer that the raw api's we have now remain exposed. But I understand there are other applications that benefit from a more dynamic api.

The ipld multiblock vector is defined like this (the Cache and the Codec is from ipld-block-builder):

```rust
pub struct List<S, T: Clone + DagCbor> {
    nodes: Cache<S, Codec, Node<T>>,
    root: Cid,
}
```

**Comment by dvc94ch** [comment]
I believe we have a block api now. Changes to the current block api should probably be discussed in a new issue if necessary.
