### ISSUE TITLE
WASM Compatibility

### ISSUE THREAD

**Issue by Gozala** [ipld/libipld#16]
I think it would be huge missed opportunity if rust-ipld does not have 1st class support for WASM compile target. I do not know what compromises it requires, but I wanted to raise this subject so we can discuss this.

**Comment by dvc94ch** [comment]
async-std needs to be ported to wasm first https://github.com/async-rs/async-std/issues/220

**Comment by dvc94ch** [comment]
@Gozala want to give this a shot? looks like most of the work on the async-std side is done.

**Comment by Gozala** [comment]
I would love to, but don’t know if I’ll be able to make time for this in coming weeks. I’ll post here if I’ll get around to this.

**Comment by dvc94ch** [comment]
Compiles on wasm using https://github.com/async-rs/async-std/tree/fix-wasm will likely work with async-std 1.6.4
