### ISSUE TITLE
Replace `prost` with `quick-protobuf`

### ISSUE THREAD

**Issue by dignifiedquire** [ipld/libipld#168]
Currently rust-libp2p and iroh are working on getting rid of the need for `protoc` in its builds. The current plan is to switch to [`quick-protobuf`](https://github.com/tafia/quick-protobuf). 

For iroh it would be very useful if libipld switched too, as we otherwise need to avoid parts of libipld.

Refs:

- https://github.com/libp2p/rust-libp2p/issues/3024
- https://github.com/n0-computer/beetle/issues/67

**Comment by vmx** [comment]
The current DAG-PB version is [not spec compliant](https://github.com/ipld/libipld/issues/139). The proper fix would be to do the same as the [JS implementation](https://github.com/ipld/js-dag-pb) and the [Go implementation](https://github.com/ipld/go-codec-dagpb) and just encode and decode manually, so no need for a protocol buffers library would be needed. Both implementations can serve as a template, depending on whether someone prefers JS or Go.

AFAICT libipld currently doesn't need `protoc` as we've checked in the generated file.

**Comment by dignifiedquire** [comment]
> AFAICT libipld currently doesn't need `protoc` as we've checked in the generated file.

There is still a dependency on `prost` which I would like to drop.

**Comment by dignifiedquire** [comment]
> The current DAG-PB version is [not spec compliant](https://github.com/ipld/libipld/issues/139). The proper fix would be to do the same as the [JS implementation](https://github.com/ipld/js-dag-pb) and the [Go implementation](https://github.com/ipld/go-codec-dagpb) and just encode and decode manually, so no need for a protocol buffers library would be needed. Both implementations can serve as a template, depending on whether someone prefers JS or Go.

That's a lot more work though.
