### ISSUE TITLE
Add dag-json implementation

### ISSUE THREAD

**Issue by Gozala** [ipld/libipld#17]
Once #8 is complete, I would like to revive https://github.com/vmx/rust-ipld/pull/2 to add dag-json support here.

We did have a lengthy conversations about where we should or should not use serde. My personal opinion had being let's use it where it's usable given it's well tested and time proved, we can always rewrite internals (to rip it off) after the fact.

If it does not feel reasonable please let me know.

**Comment by dvc94ch** [comment]
I think we can use serde for dag-json as it's not going to be very fast anyway. I can see some reasons why we should support it: debugging, compatibility and possibly because it works well with js. Does anyone have a use case for it (as in is planning to use it for something)?

**Comment by vmx** [comment]
I only have test cases as example. DagJSON is used for testing selectors in the Go implementation as it's an easy way to create fixtures with is. Example: https://github.com/ipld/go-ipld-prime/blob/530ccd6893ea4a528ffb0c7a3957754ed874be57/traversal/selector/exploreRecursive_test.go#L312

**Comment by dvc94ch** [comment]
We do have the `ipld!` macro which was created for exactly that purpose, just in case you hadn't seen it yet.

**Comment by koivunej** [comment]
@Gozala hi there! do you have any unpushed implementation of any dag-json work somewhere waiting? Looking at https://github.com/vmx/rust-ipld/pull/2 I think it looks quite a good start. If you have anything like work in progress notes or stuff like that I'd be interested in those! My question in relation to https://github.com/ipfs-rust/rust-ipfs/issues/91.
