### ISSUE TITLE
Ipld as reference

### ISSUE THREAD

**Issue by SionoiS** [ipld/libipld#181]
I want to get a reference to ```&Ipld``` without cloning the data into the enum.

Would be useful to serialize types with ```serde_json``` or ```serde_ipld_dagcbor``` without consuming them.

We know that some type could be used without cloning so maybe implement ```AsRef<Ipld>``` for builtin types as starting point?

**Comment by MarshalX** [comment]
Hi @SionoiS. Is there a way how to serialize Ipld to JSON string without describing the structure? 

That's what I try to do:
```rust
let decoded: serde_json::Value = from_ipld(ipld.clone()).unwrap();
```

that's what I get:
```
 SerdeError("invalid type: newtype struct, expected any valid JSON value"
```

**Comment by vmx** [comment]
I don't fully understand what you mean. Could you perhaps provide a minimal example?

Here's what I tried (I've added that to `serde_ipld_dacbor/tests/ipld.rs` to run it):

```rust
#[test]
fn test_ipld_reference() {
    let ipld = Ipld::String("Hello, world!".to_string());
    let data_ser = serde_ipld_dagcbor::to_vec(&ipld).unwrap();
    println!("{:?}", data_ser);
    assert!(false);
}
```

**Comment by vmx** [comment]
Oh, as I posted this, I saw that it's a pretty old issue. I was replying to a comment, that was since deleted. Does this mean that the issue got fixed? :)

**Comment by MarshalX** [comment]
@vmx ah sorry. I figured out how to do it. Thank you! Perhaps my question doesn't much about this issue 100%
