### ISSUE TITLE
Removing the Hash trait

### ISSUE THREAD

**Issue by vmx** [ipld/libipld#24]
Would it make sense to remove the `Hash` trait?

https://github.com/ipfs-rust/rust-ipld/blob/e172fbc8b7c83c751a82c0d4dde877885335152f/base/src/hash.rs#L7-L14

With the new rust-multihash version, it is just the same as `MultihashDigest`:

https://github.com/multiformats/rust-multihash/blob/a7996e06782a703fb983ed665564add0bbf89d51/src/digests.rs#L275-L285

so we could use that directly.

**Comment by dvc94ch** [comment]
Yes, probably makes sense.

**Comment by vmx** [comment]
I'll work on that once (once we have updated all the deps).
