### ISSUE TITLE
Provide mechanism to extract links from a block without building an AST

### ISSUE THREAD

**Issue by rklaehn** [ipld/libipld#58]
Building an AST is very wasteful if all you want is a set of links for e.g. pinning.

At least for Dag-CBOR, it is very easy to write a traversal that does not build an AST. See https://gist.github.com/rklaehn/62e21237e7ef8d868cfe655ad6209f28, which uses https://crates.io/crates/cbor_event .

All that would be needed is to extend the codec trait hierarchy for this operation, and then use it, e.g. in https://github.com/ipfs-rust/ipfs-embed/blob/master/src/storage/mod.rs#L75 , to get more efficient traversal of blocks for pinning.

**Comment by dvc94ch** [comment]
Love to have this feature. Any progress on it?
