### ISSUE TITLE
Parse JSON string into IPLD::Map

### ISSUE THREAD

**Issue by Tails** [ipld/libipld#70]
In the tests it is made clear that an IPLD object can be constructed using:

- the ipld!() macro
- creating a IPLD::Map from a BTreeSet

Is it also possible to parse a struct into an IPLD if it implements Serialize? Or does the ipld!() accept a JSON string?

**Comment by dvc94ch** [comment]
You want to parse dag-json into ipld? Dag json is json with support for links as cids. You should look into the dag-json codec.

**Comment by dvc94ch** [comment]
If you want to serialize a struct to ipld you can use the DagCbor derive macro.

**Comment by Tails** [comment]
Thanks you for your swift response. DagCbor was the only place I hadn't looked yet. 

I'm trying to get from a _regular_ nested JSON (string, or Rust struct) to an IPLD representation (so I can calculate the CID for the JSON blob). However, the NamedStruct in the dag-cbor-derive example already contains IPLD links. Can the DagCBOR crate encode arbitrarily nested Rust structs that do not contain IPLD links?

Like the [ipld!() macro](https://github.com/ipfs-rust/rust-ipld/blob/master/macro/src/lib.rs#L7), but programmatically with JSON from a variable or String.

**Comment by dvc94ch** [comment]
> Can the DagCBOR crate encode arbitrarily nested Rust structs that do not contain IPLD links?

Yes

**Comment by Tails** [comment]
(after writing tests for custom datastructure)

Indeed, amazing. Thank you.

**Comment by Tails** [comment]
I noticed that the ```link``` field in the NamedStruct example is commented out. Is it possible to derive a ```Ipld::Link``` from a Rust struct field?

I expected a ```libipld::Cid``` field value to parse into an ```Ipld::Link``` but Cid doesn't seem to implement Serialize/Deserialize.

**Comment by dvc94ch** [comment]
Don't remember why it's commented out, but it should work.

**Comment by Tails** [comment]
Ah indeed. I had to remove derive(Serialize, Deserialize) from the struct to make it work. Thank you for your swift replies.
