### ISSUE TITLE
Making codec calls sync

### ISSUE THREAD

**Issue by vmx** [ipld/libipld#8]
Based on https://github.com/ipld/ipld/issues/83#issuecomment-579429957 it seems that the codec encoder/decoder should be made sync again.

This would mean that the Codec Trait would change its [encode and decode methds](https://github.com/ipfs-rust/rust-ipld/blob/master/base/src/codec.rs#L18-L20) from `async` to sync
(the CBOR implementation of it is here: https://github.com/ipfs-rust/rust-ipld/blob/195df89087a31397c4a37a07e0694ded8ce0ad02/dag-cbor/src/lib.rs#L26-L34)

@dvc94ch is that correct?

**Comment by Gozala** [comment]
I can take this

**Comment by dvc94ch** [comment]
Before making any more changes we should probably start by adding some benchmarks, and then validate that this does make a huge difference.

**Comment by vmx** [comment]
I'm always in favour of having benchmarks, though in this case I don't think it has a high priority. I would accept a PR making things sync even without benchmarks. Performance surely is a concern at one point, but I don't think we are there yet.

**Comment by dvc94ch** [comment]
Well it is very useful to have an idea what takes a lot of time and what doesn't. There are huge surprises and regularly checking is advisable. For example using base58 for cids for anything other than displaying to the user is extremely unadvisable. Something I'd not have thought before looking at the flamegraph.

**Comment by Gozala** [comment]
Maybe it is a good time to ask what is the motivation for switching to sync. I was assuming that async lead to poor performance. If that is not the case it would be to know the motivation. Maybe experience of working with async is poorer ? 

Anyway it seems like it’s good to know what the goal is so we can verify afterwards that it is accomplished. If it is performance we should definitely check that numbers are improved, if it is something else let’s make sure that our assumption about this change are grounded in some evidence

**Comment by vmx** [comment]
To me the motivation for having it sync would be to have easier to deal with code, if the performance is not worse by an order of a magnitude compared to the async one.

**Comment by dvc94ch** [comment]
I expect there to be an order of magnitude improvement, I think the problem is that the compiler doesn't support async traits yet, it missed a lot of inlining/optimization improvements. I'll have to look into it again, will probably get around to it soon.

**Comment by dvc94ch** [comment]
It being easier to deal with code is not a reason. Using async means that the parser works on a stream directly. Sending ipld over tcp/uds would require delimiting the data, buffering it and then parsing the buffer. That means that it's slightly more work for the programmer.

**Comment by Gozala** [comment]
@dvc94ch @vmx do we have consensus on whether we should block this on #18 or are we comfortable tackling two independent of each other ? I personally would prefer to do it independently to reduce the scope. I imagine we could always validate numbers by running benchmarks against current head and the new head.

**Comment by Gozala** [comment]
@vmx I think your position is that it would be easier to deal with sync interface and that is why we should do it. I think I agree as it's just as easy to use from both sync and async code.

However if I am understanding argument from @dvc94ch that trade-off is that you no longer work with a stream and need to buffer which adds some complexity.

Is that a fare summary ? I am not sure if two can be reconciled in any way. But given that @dvc94ch has indicated https://github.com/ipld/ipld/issues/83#issuecomment-579429957 desire to switch to sync I am working under the assumption that there is a consensus to do so.

**Comment by Gozala** [comment]
Also I want to make sure that point made by @dignifiedquire at https://github.com/ipld/ipld/issues/83 has benig considered (inline for convenience)

> @dvc94ch which parts go slower? I think any serious implementation that is future oriented and high perf, should use async definitely for disk io, and storage.

**Comment by dvc94ch** [comment]
Maybe I'm wrong, you can easily prove me wrong if that is the case. I'll investigate it and report back once I get around to it. However I already replied to that point.
To be honest I'm also a bit confused why me making a falsifiable claim/hypothesis is causing so much discussion, when it could easily be falsified, it's not like benchmarking stuff early is a waste of time.
And it is a genuine concern of mine even if I turn out to be completely wrong, sorry if you feel obligated or hindered to do something in any way, just ignore the issue for now....

**Comment by Gozala** [comment]
@dvc94ch my reading is @vmx wants to see this change and it’s not related to the performance. On the other I think @dignifiedquire has an opposite view. 

I didn’t meant to press on whether your assumptions are valid. I just want to make sure we can all align.

I’m also almost done with a patch for this, plan on submitting it tomorrow & after that I’ll attempt to add benchmarks as per your suggestion so we can also consider numbers.

**Comment by vmx** [comment]
To explain, why I brought up that I don't care about the perf at the moment that much: I also thought @dvc94ch and I had agreement that it should be sync and I didn't want to take extra time from @Gozala to write benchmarks, when we want to change anyway. So for me it was a time investment/benefit trade-off.

I'm not against benchmarking in general :)
