### ISSUE TITLE
Compact, validated storage of ipld data

### ISSUE THREAD

**Issue by rklaehn** [ipld/libipld#88]
We need something similar to the `Opaque` type that stores an opaque IPLD dag as a single `Box<[u8]>` or similar. It should be able to read from/write to dag-cbor with a small, constant number of allocations no matter how big the object is.

Ideally this should internally use dag-cbor, but be able to read from/write to dag-json as well.

In serde, this can be implemented using https://docs.rs/serde-transcode/1.1.0/serde_transcode/ , and some serde formats have hackish built in support, e.g. for serde json https://docs.serde.rs/serde_json/value/struct.RawValue.html .

The use case is that you have a system that handles (forwards, caches, ...) a large number of large events with arbitrary payloads, but is not interested in the fields of the payload. Parsing the payload into an IPLD AST is prohibitively wasteful.

**Comment by rklaehn** [comment]
You might think this is pointless, but when we introduced Opaque it was literally a factor of 10 improvement in memory usage and thus number of events we could afford to keep cached. It also improved performance quite a bit. See https://actyx.slack.com/archives/CNDETHH6U/p1571410960280300

**Comment by dvc94ch** [comment]
Closing as duplicate of #95
